image: fpco/stack-build-small:lts-15.5

services:
  - docker:dind

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  CI_AWS_ECS_CLUSTER: "botty-mccluster"
  CI_AWS_ECS_SERVICE: "botty-mcservice"
  CI_AWS_ECS_TASK_DEFINITION: "first-run-task-definition"
  REPOSITORY_URL: 571275409555.dkr.ecr.ap-southeast-2.amazonaws.com/bottymcbotterson

cache: 
  paths:
    - .stack-root
    - .stack-work

stages:
  - build
  - publish
  - deploy

application_build:
  stage: build
  script:
    - stack install --local-bin-path ./build --system-ghc
    - cp -R --verbose res ./build/
  artifacts:
    paths:
      - build/*
    expire_in: 1 week

docker_build:
  stage: build
  image: docker:latest
  script:
    - ls -al
    - docker build --no-cache -t $REPOSITORY_URL .
    - docker tag $REPOSITORY_URL $REPOSITORY_URL:test

docker_publish:
  stage: publish
  script:
    - ls -al
    - docker push $REPOSITORY_URL:test

deploy_staging:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecs register-task-definition ${CI_AWS_ECS_TASK_DEFINITION}
  environment:
    name: staging
    url: www.example.com
  only:
    - master
  when: manual