image: fpco/stack-build-small:lts-15.5

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  CI_AWS_ECS_CLUSTER: "botty-mccluster"
  CI_AWS_ECS_SERVICE: "botty-mcservice"
  CI_AWS_ECS_TASK_DEFINITION: "first-run-task-definition"

cache: 
  paths:
    - .stack-root
    - .stack-work

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - stack install --local-bin-path ./build --system-ghc
    - cp -R --verbose res ./build/
  artifacts:
    paths:
      - build/*
    expire_in: 1 week

deploy_staging:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecs register-task-definition ${CI_AWS_ECS_TASK_DEFINITION}
  environment:
    name: staging
    url: www.example.com
  only:
    - master
  when: manual