image: fpco/stack-build-small:lts-15.5

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache: 
  paths:
    - .stack-root
    - .stack-work

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - stack install --local-bin-path ./build
  artifacts:
    paths:
      - build

deploy_staging:
  stage: deploy
  script:
    - "echo Deploying to staging server"
  environment:
    name: staging
    url: www.example.com
  only:
    - master
  when: manual