image: fpco/stack-build:lts-15.5
variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache: 
  paths:
    - .stack-root
    - .stack-work

stages:
  - build

build:
  stage: build
  script:
    - stack build
